version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: continuumio/miniconda3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/bsipos/bsipos-conda

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
            keys:
            #- v1-dependencies-{{ checksum "conda_base.txt" }}
            # fallback to using the latest cache if no exact match is found
            - cache-v2-

      - run:
          name: install dependencies
          command: |
            conda init -q bash
            source $HOME/.bashrc
            git config --global user.email "sbotond"
            git config --global user.name "Botond Sipos"
            git config --global core.editor ""
            rm -fr conda_base
            apt-get update && apt-get upgrade -y;
            apt-get install -y build-essential cmake;
            if [ ! -d isONclust2 ]
            then git clone --recursive https://github.com/nanoporetech/isONclust2.git
            fi;

      - save_cache:
            paths:
              - ./conda_base
            key: cache-v2-

      - run:
          name: build isONclust2 (linux)
          command: |
            cd isONclust2;
            git pull --force
            mkdir build; cd build
            cmake ..
            make -j 2;
            cd bin;
            ./isONclust2 version
            
      - run:
          name: test isONclust2 (linux)
          command: |
            source $HOME/.bashrc
            cd isONclust2/build/bin;
            ./test_isONclust2;
            
